# Generated by Django 2.2.7 on 2019-11-06 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='entité')),
                ('address', models.CharField(max_length=100, verbose_name='adresse')),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_at', models.DateField(verbose_name='début de la mission')),
                ('end_at', models.DateField(verbose_name='fin de la mission')),
            ],
        ),
        migrations.CreateModel(
            name='UserManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100, verbose_name='prénom')),
                ('lastName', models.CharField(max_length=100, verbose_name='nom')),
                ('email', models.EmailField(max_length=100, null=True, unique=True, verbose_name='email')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='adresse')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missions', models.ForeignKey(on_delete=False, to='management.Mission')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('usermanage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='management.UserManage')),
                ('job', models.CharField(max_length=100, verbose_name='métier')),
                ('company', models.OneToOneField(on_delete=False, to='management.Company')),
            ],
            bases=('management.usermanage',),
        ),
        migrations.AddField(
            model_name='mission',
            name='resources',
            field=models.ForeignKey(on_delete=False, to='management.Resource'),
        ),
    ]
