# Generated by Django 2.2.7 on 2019-11-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('address', models.CharField(max_length=100, verbose_name='adresse')),
            ],
            options={
                'verbose_name': 'entité',
                'verbose_name_plural': 'entités',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100, verbose_name='prénom')),
                ('lastName', models.CharField(max_length=100, verbose_name='nom')),
                ('email', models.EmailField(max_length=100, null=True, unique=True, verbose_name='email')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='adresse')),
                ('job', models.CharField(max_length=100, verbose_name='métier')),
                ('company', models.OneToOneField(null=True, on_delete=False, to='management.Company')),
            ],
            options={
                'verbose_name': 'ressource',
                'verbose_name_plural': 'ressources',
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_at', models.DateField(verbose_name='début de la mission')),
                ('end_at', models.DateField(verbose_name='fin de la mission')),
                ('resources', models.ForeignKey(null=True, on_delete=False, to='management.Resource')),
            ],
            options={
                'verbose_name': 'mission',
                'verbose_name_plural': 'missions',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('address', models.CharField(max_length=100, verbose_name='adresse')),
                ('missions', models.ForeignKey(null=True, on_delete=False, to='management.Mission')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
            },
        ),
    ]
