# Generated by Django 2.2.7 on 2019-11-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='codeName',
            field=models.CharField(default='', max_length=200, verbose_name='nom de code'),
        ),
        migrations.AddField(
            model_name='mission',
            name='description',
            field=models.TextField(null=True, verbose_name='description'),
        ),
    ]
