# Generated by Django 2.2.7 on 2019-11-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20191107_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='begin_at',
            field=models.DateTimeField(null=True, verbose_name='début de la mission'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='end_at',
            field=models.DateTimeField(null=True, verbose_name='fin de la mission'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='job',
            field=models.CharField(default='', max_length=100, verbose_name='métier'),
        ),
    ]
