# Generated by Django 2.2.7 on 2019-11-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20191107_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='missions',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='resources',
        ),
        migrations.AddField(
            model_name='mission',
            name='client',
            field=models.ForeignKey(null=True, on_delete=False, to='management.Client'),
        ),
        migrations.AddField(
            model_name='resource',
            name='mission',
            field=models.ForeignKey(null=True, on_delete=False, to='management.Mission'),
        ),
    ]
