# Generated by Django 2.2.7 on 2019-11-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20191107_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='company',
            field=models.ForeignKey(null=True, on_delete=False, to='management.Company'),
        ),
    ]
