# Generated by Django 2.2.7 on 2019-11-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20191107_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='in_progress',
            field=models.BooleanField(default=False, verbose_name='en cours'),
        ),
    ]
