# Generated by Django 2.2.7 on 2019-11-12 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_mission_in_progress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mission',
            old_name='codeName',
            new_name='code_name',
        ),
    ]
