# Generated by Django 2.2.7 on 2019-11-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20191112_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='begin_at',
            field=models.DateField(null=True, verbose_name='début de la mission'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='end_at',
            field=models.DateField(null=True, verbose_name='fin de la mission'),
        ),
    ]
