# Generated by Django 2.2.7 on 2019-11-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_auto_20191112_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='company',
            field=models.ForeignKey(null=True, on_delete=False, related_name='companie', related_query_name='companies', to='management.Company'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='mission',
            field=models.ForeignKey(null=True, on_delete=False, related_name='mission', related_query_name='missions', to='management.Mission'),
        ),
    ]
