# Generated by Django 2.2.7 on 2019-11-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_auto_20191112_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='client',
            field=models.ForeignKey(null=True, on_delete=False, related_name='client', related_query_name='clients', to='management.Client'),
        ),
    ]
