# Generated by Django 2.2.7 on 2019-11-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_auto_20191112_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='client',
        ),
        migrations.AddField(
            model_name='client',
            name='missions',
            field=models.ForeignKey(null=True, on_delete=False, related_name='c_mission', related_query_name='c_missions', to='management.Mission'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='company',
            field=models.ForeignKey(null=True, on_delete=False, related_name='r_companie', related_query_name='r_companies', to='management.Company'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='mission',
            field=models.ForeignKey(null=True, on_delete=False, related_name='r_mission', related_query_name='r_missions', to='management.Mission'),
        ),
    ]
