# Generated by Django 2.2.7 on 2019-11-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_auto_20191112_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='missions',
        ),
        migrations.AddField(
            model_name='mission',
            name='client',
            field=models.ForeignKey(null=True, on_delete=False, related_name='c_mission', related_query_name='c_missions', to='management.Client'),
        ),
    ]
