# Generated by Django 2.2.7 on 2019-11-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_auto_20191112_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='client',
        ),
        migrations.AddField(
            model_name='mission',
            name='clients',
            field=models.ForeignKey(null=True, on_delete=False, related_name='m_client', related_query_name='m_clients', to='management.Client'),
        ),
        migrations.AddField(
            model_name='mission',
            name='resources',
            field=models.ForeignKey(null=True, on_delete=False, related_name='m_resource', related_query_name='m_resources', to='management.Resource'),
        ),
    ]
