# Generated by Django 2.2.7 on 2019-11-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_auto_20191112_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='resources',
        ),
        migrations.AlterField(
            model_name='mission',
            name='clients',
            field=models.ForeignKey(null=True, on_delete=False, related_name='m_client', to='management.Client'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='company',
            field=models.ForeignKey(null=True, on_delete=False, related_name='r_companie', to='management.Company'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='mission',
            field=models.ForeignKey(null=True, on_delete=False, related_name='r_mission', to='management.Mission'),
        ),
    ]
