# Generated by Django 2.2.7 on 2019-11-12 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_auto_20191112_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mission',
            old_name='clients',
            new_name='client',
        ),
    ]
