# Generated by Django 2.2.7 on 2019-11-13 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_auto_20191112_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='lastName',
            new_name='last_name',
        ),
    ]
