# Generated by Django 2.2.7 on 2019-11-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_auto_20191113_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='client',
            field=models.ForeignKey(null=True, on_delete=False, related_name='m_client', related_query_name='m_clients', to='management.Client'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='company',
            field=models.ForeignKey(null=True, on_delete=False, related_name='r_companie', related_query_name='r_companies', to='management.Company'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='mission',
            field=models.ForeignKey(null=True, on_delete=False, related_name='r_mission', related_query_name='r_missions', to='management.Mission'),
        ),
    ]
